name: Lighthouse Report

on:
  repository_dispatch:
    types: [generate-lighthouse-report]

jobs:
  print_payload:
    runs-on: ubuntu-latest
    steps:
      - name: Print Webhook Payload
        run: |
          echo "Received webhook payload:"
          echo "${{ toJson(github.event.client_payload) }}"
